version: 2.1

orbs:
  checkov: bridgecrew/checkov@0.0.4

jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: '.'
          soft-fail: true
          output: "junitxml"
          api-key: BC-API-KEY
